#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias valgrind='valgrind --leak-check=full --show-reachable=yes --track-fds=yes'
alias callgrind='\valgrind --tool=callgrind'
alias cachegrind='\valgrind --tool=cachegrind'
alias helgrind='\valgrind --tool=helgrind'
alias chromium='chromium --incognito'

PS1='[\u@\h \W]\$ '
